{$IFDEF debug}
  {$A-,B-,D+,E+,F+,G-,I+,L+,N+,M 16384 0 655360,O-,P+,Q+,R+,S+,T-,V-,X+,Y+}
{$ELSE}
  {$A-,B-,D-,E+,F+,G-,I+,L-,N+,M 16384 0 655360,O-,P+,Q-,R-,S-,T-,V-,X+,Y-}
{$ENDIF}
unit Consts;

interface

const
  PointerSize = SizeOf(Pointer);

type
  String1 = string[1];
  String2 = string[2];
  String3 = string[3];
  String4 = string[4];
  String5 = string[5];
  String6 = string[6];
  String7 = string[7];
  String8 = string[8];
  String9 = string[9];
  String10 = string[10];
  String11 = string[11];
  String12 = string[12];
  String13 = string[13];
  String14 = string[14];
  String15 = string[15];
  String16 = string[16];
  String17 = string[17];
  String18 = string[18];
  String19 = string[19];
  String20 = string[20];
  String25 = string[25];
  String30 = string[30];
  String35 = string[35];
  String40 = string[40];
  String45 = string[45];
  String50 = string[50];
  String75 = string[75];
  String80 = string[80];
  String100 = string[100];

implementation

end.